### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Burndowntheworld** [lmnyx/hypixel-skyblock-item-generator#1]
the discord link is no longer working.

**Comment by rezemoe** [comment]
@Burndowntheworld This repository was not updated for 3 years and the community related to this repository has died ever since too, I am not sure what did you expect. If you want something specific, please tell me, or if it's more of a private matter [reze.moe](https://reze.moe) has the link to the new Discord server, but it is not related to Minecraft or Hypixel in any way shape or form.
